name: datatable_sortable_example
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_datagrid: ^19.3.46
  http: ^0.13.4
  provider: ^6.0.1
  fl_chart: ^0.40.2
  google_fonts: ^2.1.0
  json_annotation: ^4.3.0
  json_serializable: ^6.0.1
  build_runner: ^2.1.4
  intl: ^0.17.0
  table_calendar: ^3.0.3
  flutter_screenutil: ^5.0.0+2
  smooth_page_indicator: ^1.0.0+2
  colorize_text_avatar: ^1.0.2
  simple_animations: ^4.0.1
  flutter_svg: ^0.23.0+1
  bloc: ^7.2.1
  cupertino_icons: ^1.0.2
  dhttpd: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true